SELECT c.CUST_ID,c.CUST_TYPE_CD,(i.FIRST_NAME+i.LAST_NAME) as name
FROM CUSTOMER c
INNER JOIN INDIVIDUAL i ON c.CUST_ID = i.CUST_ID
UNION
SELECT c.CUST_ID,c.CUST_TYPE_CD,b.NAME as name
FROM CUSTOMER c
INNER JOIN BUSINESS b ON c.CUST_ID = b.CUST_ID


SELECT * FROM BU